const SET_EDITOR_TEXT = 'SET_EDITOR_TEXT'
const SAVE_CONTENT_IN_STORE = 'SAVE_CONTENT_IN_STORE'
const GET_CONTENT_FROM_STORE = 'GET_CONTENT_FROM_STORE'
const SELECT_ALL = 'SELECT_ALL'
const SET_THEME = 'SET_THEME'
const SET_ALLOW_HTML = 'SET_ALLOW_HTML'

module.exports = {
  SET_EDITOR_TEXT,
  SAVE_CONTENT_IN_STORE,
  GET_CONTENT_FROM_STORE,
  SELECT_ALL,
  SET_THEME,
  SET_ALLOW_HTML
}
