name: Markit CD
on: [push]
jobs: 
  build: 
    name: MarkItCI_CD
    runs-on: "${{ matrix.os }}"
    steps: 
      - 
        name: checkout
        uses: actions/checkout@v2
      - 
        name: "set tag version"
        run: "echo \"::set-env name=version::${GITHUB_REF##*v}\"\n"
        shell: bash
      - 
        if: runner.os=='linux'
        name: "set artifact&asset name for ubuntu"
        run: |
            echo "::set-env name=artifactname::markit_${version}_amd64.deb"
            echo "::set-env name=assetname::markit_${version}_amd64.deb"
      - 
        if: runner.os=='windows'
        name: "set artifact&asset name for windows"
        run: |
            echo "::set-env name=artifactname::markit Setup ${version}.exe"
            echo "::set-env name=assetname::markit Setup ${version}.exe"
        shell: bash
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: "Upload Release Assets"
        uses: saketh-kowtha/markit@v1-release
        with: 
          asset_name: "${{ env.assetname }}"
          file: "./electron/dist/${{ env.artifactname }}"
          overwrite: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ github.ref }}"
    strategy: 
      matrix: 
        os: 
          - ubuntu-latest
          - windows-latest
