jobs:
  build:
    name: MarkItCI_CD

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set tag version #If needed, here you can can compare the value form package.json with ${GITHUB_REF##*v}.
        shell: bash
        run: |
          echo "::set-env name=version::${GITHUB_REF##*v}"

      - name: set artifact&asset name for ubuntu
        if: runner.os=='linux'
        run: |
          echo "::set-env name=artifactname::markit_${version}_amd64.deb"
          echo "::set-env name=assetname::markit_${version}_amd64.deb"
      - name: set artifact&asset name for windows
        shell: bash
        if: runner.os=='windows'
        run: |
          echo "::set-env name=artifactname::markit Setup ${version}.exe"
          echo "::set-env name=assetname::markit Setup ${version}.exe"
      - name: Upload Release Assets
        uses: saketh-kowtha/markit@v1-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./electron/dist/${{ env.artifactname }}"
          asset_name: ${{ env.assetname }}
          tag: ${{ github.ref }}
          overwrite: true